language: php

notifications:
  email:
    on_success: never

php:
  - '7.4'

before_script:
  - make dev-from-scratch

script: make CI

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar;
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
